function [r] = CheckDistrictName(~,districtName)
  % returns true if district name is one of the fifty states
  r = 0;
  if length(districtName) < 4
    return;
  endif

  r = ismember(substr(districtName,1,2), ...
    {"AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",...
     "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",...
     "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",...
     "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",...
     "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY"});
endfunction
